# This is proxy config
[http]
    addr =":8080"
    ssl_addr =":8443"
    read_timeout = 10
    write_timeout = 10
    max_header_bytes = 20
    allow_ip = [
        "127.0.0.1",
        "192.168.1.1"
    ]